version: '3.8'
services:
  mongo:
    image: mongo:8.0
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - api_network
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://localhost:27017/ 
  flask_app:
    image: api_todo:1.8
    build: .
    container_name: api_todo
    ports:
      - "5002:5002"
    depends_on:
      - mongo
    environment:
      FLASK_ENV: development
      MONGO_URI: mongodb://mongo:27017/todo  
    networks:
      - api_network
networks:
  api_network:
    driver: bridge
